-- заполнение таблицы places

INSERT INTO `plases` (`id`, `name_plase`) VALUES (1, 'Willmouth');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (2, 'Smithamville');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (3, 'Schultzborough');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (4, 'Murazikshire');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (5, 'Huelsshire');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (6, 'Goldnershire');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (7, 'South Mariomouth');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (8, 'Abbottberg');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (9, 'Volkmanland');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (10, 'Lake Kaylie');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (11, 'New Jaysonhaven');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (12, 'West Winstonview');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (13, 'East Felicita');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (14, 'Burniceshire');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (15, 'Laneyborough');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (16, 'East Osborneview');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (17, 'Gisselleton');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (18, 'West Dariana');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (19, 'North Joyce');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (20, 'Celinefurt');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (21, 'West Briannetown');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (22, 'Smithville');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (23, 'Alvinastad');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (24, 'East Melody');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (25, 'East Kaleighside');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (26, 'Lake Malinda');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (27, 'Jalynside');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (28, 'Dariuston');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (29, 'Icieland');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (30, 'North Lucymouth');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (31, 'Berrychester');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (32, 'Lake Alexa');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (33, 'South Delphachester');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (34, 'South Casandrastad');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (35, 'East Pascale');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (36, 'New Kendrick');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (37, 'Lake Zechariahtown');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (38, 'New Thomas');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (39, 'Litteltown');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (40, 'Lake Giles');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (41, 'Bryonfurt');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (42, 'New Damianfurt');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (43, 'Ashleighmouth');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (44, 'Sigmundhaven');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (45, 'West Elsatown');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (46, 'Port Alvinaland');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (47, 'North Danielaport');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (48, 'Carlottamouth');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (49, 'Lake Colleen');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (50, 'Dereckburgh');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (51, 'Mikaylafort');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (52, 'Jonasmouth');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (53, 'Dachberg');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (54, 'South Carrie');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (55, 'Blicktown');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (56, 'Alfburgh');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (57, 'New Cicero');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (58, 'Rueckerton');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (59, 'Windlerville');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (60, 'Port Obie');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (61, 'North Hans');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (62, 'Angushaven');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (63, 'Lake Kenna');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (64, 'Hunterhaven');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (65, 'Lenorechester');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (66, 'Clementinaland');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (67, 'Port Adanburgh');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (68, 'New Randy');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (69, 'South Amy');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (70, 'South Sigurdport');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (71, 'Zoeyshire');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (72, 'Lake Alexane');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (73, 'Jasonmouth');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (74, 'Roelview');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (75, 'Antonettaville');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (76, 'Christiansentown');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (77, 'Lednerborough');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (78, 'Jeffryberg');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (79, 'West Horacioberg');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (80, 'Lemuelborough');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (81, 'East Manley');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (82, 'Borerchester');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (83, 'Dietrichborough');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (84, 'New Bailee');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (85, 'Gaystad');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (86, 'New Sabinastad');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (87, 'West Irmafurt');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (88, 'Vilmachester');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (89, 'Naomifort');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (90, 'Satterfieldfort');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (91, 'South Dayneport');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (92, 'South Vance');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (93, 'New Osborne');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (94, 'Juvenalville');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (95, 'Port Kobe');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (96, 'West Virgie');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (97, 'Hubertmouth');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (98, 'New Sedricktown');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (99, 'Sammiemouth');
INSERT INTO `plases` (`id`, `name_plase`) VALUES (100, 'Odamouth');


